---
- name: Import grafana dashboards through API
  uri:
    url: "https://k8s-minikub/api/dashboards/db"
    user: "admin"
    password: "admin"
    force_basic_auth: true
    method: POST
    validate_certs: no
    body_format: json
    body: >
      {
        "dashboard": {{ lookup("file", item) }},
        "overwrite": true,
        "message": "Updated by ansible"
      }
  with_fileglob:
    - "templates/*.json"
