---
- name: install packages
  become: yes
  become_method: sudo
  yum: name={{item}} state=present
  with_items:
    - wget
    - unzip
    - vim
    - socat 
    - git

- name: disable firewall
  become: yes
  become_method: sudo
  raw: "systemctl disable firewalld && systemctl stop firewalld"
