apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-state-metrics
  labels:
    prometheus-app: kube-state-metrics
spec:
  jobLabel: prometheus-app
  selector:
    matchLabels:
      prometheus-app: kube-state-metrics
  namespaceSelector:
    matchNames:
    - default
    - kube-system
  endpoints:
  - port: http-metrics
    interval: 1s
